In [28]:
# Fixing imports
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as tts
from sklearn.datasets import fetch_openml
from PIL import Image, ImageTk
import time

In [19]:
# Loading dataset and splitting to training and test set
x, y = fetch_openml('mnist_784', version=1, return_X_y=True)
x_train, x_test, y_train, y_test = tts(x, y, test_size=0.25, random_state=0)
y_train = y_train.reshape(len(y_train), 1)
y_test = y_test.reshape(len(y_test), 1)

In [20]:
class DigitRecognizer():
    def __init__(self):
        self.x = tf.placeholder(tf.float32)
        self.y = tf.placeholder(tf.float32)
        
        self.W = tf.Variable(np.zeros(shape=(784, 10), dtype=np.float32))
        self.b = tf.Variable(np.zeros(shape=(1, 10), dtype=np.float32))
        
        logits = tf.matmul(self.x, self.W) + self.b
        self.f = tf.nn.softmax(logits)
        
        self.loss = tf.losses.softmax_cross_entropy(self.y, logits)

In [29]:
model = DigitRecognizer()
mini_op = tf.train.GradientDescentOptimizer(100).minimize(model.loss)

session = tf.Session()
session.run(tf.global_variables_initializer())

start = time.time()

for i in range(1000):
    session.run(mini_op, {model.x: x_train, model.y: y_train})


end = time.time()
print("Runtime: %.2f" % (end - start))

W, b, loss = session.run([model.W, model.b, model.loss], {model.x: x_test, model.y: y_test})

Runtime: 179.38


In [27]:
print(loss)
print(W)
print(b)

102.5611
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[435187. 435187. 435187. 435187. 435187. 435187. 435187. 435187. 435187.
  435187.]]
